// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SalaryService.DataAccess.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20251112063309_AddNewFieldsToEmployee")]
    partial class AddNewFieldsToEmployee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BirthDate")
                        .HasColumnType("text");

                    b.Property<string>("CorporateEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHub")
                        .HasColumnType("text");

                    b.Property<string>("GitLab")
                        .HasColumnType("text");

                    b.Property<bool>("IsBlankEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCurrentEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("PersonalEmail")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int[]>("Specializations")
                        .HasColumnType("integer[]");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkerTime")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorporateEmail")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CorporateEmail = "ceo@tourmalinecore.com",
                            FirstName = "Ceo",
                            GitHub = "@ceo.github",
                            GitLab = "@ceo.gitlab",
                            IsBlankEmployee = true,
                            IsCurrentEmployee = true,
                            IsSpecial = false,
                            LastName = "Ceo",
                            MiddleName = "Ceo",
                            PersonalEmail = "ceo@gmail.com",
                            Phone = "88006663636",
                            TenantId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CorporateEmail = "inner-circle-admin@tourmalinecore.com",
                            FirstName = "Admin",
                            IsBlankEmployee = true,
                            IsCurrentEmployee = true,
                            IsSpecial = true,
                            LastName = "Admin",
                            MiddleName = "Admin",
                            PersonalEmail = "inner-circle-admin@gmail.com",
                            TenantId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            CorporateEmail = "trial@tourmalinecore.com",
                            FirstName = "Trial",
                            IsBlankEmployee = true,
                            IsCurrentEmployee = true,
                            IsSpecial = false,
                            LastName = "Trial",
                            MiddleName = "Trial",
                            PersonalEmail = "trial@gmail.com",
                            TenantId = 1L
                        });
                });

            modelBuilder.Entity("Core.WorkingPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("WorkingDaysInMonth")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WorkingDaysInYear")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WorkingDaysInYearWithoutVacation")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WorkingDaysInYearWithoutVacationAndSick")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WorkingHoursInMonth")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("WorkingPlan");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            WorkingDaysInMonth = 16.916666666666666666666666667m,
                            WorkingDaysInYear = 247m,
                            WorkingDaysInYearWithoutVacation = 223m,
                            WorkingDaysInYearWithoutVacationAndSick = 203m,
                            WorkingHoursInMonth = 135.33333333333333333333333334m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
